### PR TITLE
Add read/write for 128-bit and 256-bit BigInt values

### PR DESCRIPTION
**Pull request by danield9tqh**
Hey @chjj we are using your library and have some use cases for larger BigInt serialization. I've added this code to our codebase but wanted to contribute in case this was useful to others too. I've tried to follow coding conventions as I see them. Let me know if this is useful or if you have any other comments. Thanks!

### CODE REVIEW

**Comment by NullSoldier** [comment]
To add more information, our Layer 1 Iron Fish needs this and we've added this code to our code base while we wait for this to be merged. https://github.com/iron-fish/ironfish

**Comment by chjj** [comment]
Please add the accompanying big endian functions to the reader/writers (for completeness).

**Comment by danield9tqh** [comment]
@chjj Added the BE writer+reader as well

**Comment by chjj** [comment]
Published to NPM in v1.2.0.

**Pull request merged**
